---
- name: Change ticket with notes
  hosts: localhost
  gather_facts: no
  connection: local

  tasks:
  - name: include vars
    include_vars: change_request_vars.yml

  - name: Modify a change request status to closed
    snow_record:
      state: present
      table: incident
      username: "{{ sn_username }}"
      password: "{{ sn_password }}"
      instance: "{{ sn_instance }}"
      number: "{{ sn_incident_number }}"
      data:
        close_code: Closed/Resolved by Caller
        close_notes: Closing the ticket
        state: 6
    register: incident
    
  - name: Modify a change request status to Review
    snow_record:
      state: present
      table: incident
      username: "{{ sn_username }}"
      password: "{{ sn_password }}"
      instance: "{{ sn_instance }}"
      number: "{{ sn_incident_number }}"
      data:
        state: 7
    register: incident
 


  - debug: 
      var: incident.record.close_code
