- name: Onboard Users and Group
  hosts: all
  tasks:
   - name: Add group "Salesforce" to remote server
     group:
       name: salesforce
       gid: 2010
       state: present

   - name: Add group "Office" to remote server
     group:
       name: office
       gid: 2011
       state: present

   - name: Add group "Genomics" to remote server
     group:
       name: genomics
       gid: 2012
       state: present 

   - name: Add user "sysadmin" to remote server
     user:
       name: sysadmin
       comment: "Privileged User"
       uid: 2001
       group: salesforce
       groups: office,genomics
       append: yes
       shell: /bin/bash
       generate_ssh_key: yes
       ssh_key_bits: 2048
       ssh_key_file: .ssh/id_rsa

   - name: Add user "Obejwan" to remote server
     user:
       name: obejwan
       password: ''
       comment: "Accountant UnPrivileged User"
       uid: 2002
       group: office
       shell: /bin/bash
       generate_ssh_key: yes
       ssh_key_bits: 2048
       ssh_key_file: .ssh/id_rsa

   - name: Add user "Yoda" to remote server
     user:
       name: yoda
       password: ''
       comment: "Content creator UnPrivileged User"
       uid: 2003
       group: office
       shell: /bin/bash
       generate_ssh_key: yes
       ssh_key_bits: 2048
       ssh_key_file: .ssh/id_rsa

   - name: Add user "rajesh" to remote server
     user:
       name: rajesh
       password: ''
       comment: "Sales Force Privileged User"
       uid: 2004
       group: salesforce
       groups: office,genomics
       append: yes
       shell: /bin/sh
       generate_ssh_key: yes
       ssh_key_bits: 2048
       ssh_key_file: .ssh/id_rsa

...
